In [2]:
import os 
import pandas as pd
import numpy as np


import nltk


#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)

In [97]:
Dir_timestamps = '/work/desai-lab/ABCAI/ABC_neuroimaging-master/stimuli_and_design/timestamps/'
List_story = os.listdir(Dir_timestamps)
List_story = [file for file in List_story if '.times.' in file]
Lists_words = []
for file in List_story:

    # Using readlines()
    texts = open(os.path.join(Dir_timestamps,file), 'r')
    Lines = texts.readlines()
    List_words = []
    for line in Lines:
        if not '@ @' in line:
            List_words.append(line.replace(' \n','').replace('\n','').replace('  ',' '))
    df = pd.DataFrame(List_words)
    df.columns = ['raw']
    df[['word','onset','offset']] = df['raw'].str.split(' ',expand=True)
    df['audio'] = file.replace('.times.txt','')
    Lists_words.append(df)
dfs = pd.concat(Lists_words,ignore_index = True)

tags = nltk.pos_tag(dfs['word'])
for i,tag in enumerate(tags):
    dfs.loc[i,'PoS_tag_full'] = tag[1]
dfs

,raw,word,onset,offset,audio,PoS_tag_full
0,Koko 1.700 2.300,Koko,1.700,2.300,Jacob_Koko,NNP
1,did 4.500 4.900,did,4.500,4.900,Jacob_Koko,VBD
2,you 4.900 5,you,4.900,5,Jacob_Koko,PRP
3,know 5 5.200,know,5,5.200,Jacob_Koko,VBP
4,that 5.200 5.500,that,5.200,5.500,Jacob_Koko,IN
...,...,...,...,...,...,...
43398,to 355 355.400,to,355,355.400,Allison_MetaphorsRepeatedNames,TO
43399,look 355.400 355.600,look,355.400,355.600,Allison_MetaphorsRepeatedNames,VB
43400,for 355.600 355.800,for,355.600,355.800,Allison_MetaphorsRepeatedNames,IN
43401,another 355.800 355.900,another,355.800,355.900,Allison_MetaphorsRepeatedNames,DT
43402,house 355.900 356.500,house,355.900,356.500,Allison_MetaphorsRepeatedNames,NN

In [50]:
df_scope = pd.read_csv('/work/desai-lab/xuanyang/Project/dataset/SCOPE/generateTiming/SCOPE_all.csv',encoding="latin-1")
#df_scope = pd.read_csv('E:/phd/project/Nastase/wordlevel/Passage/codes/generateTiming/SCOPE_all.csv', index_col=0,encoding="latin-1")
df_scope

,Word,Freq_HAL,Freq_KF,Freq_SUBTLEXUS,Freq_SUBTLEXUS_Zipf,Freq_SUBTLEXUK,Freq_SUBTLEXUK_Zipf,Freq_Blog,Freq_Twitter,Freq_News,...,LexicalD_ACC_A_MALD,LexicalD_ACC_A_AELP,Naming_RT_ELP,Naming_RT_ELP_z,Naming_ACC_ELP,SemanticD_RT_Calgary,SemanticD_RT_Calgary_z,SemanticD_ACC_Calgary,Recog_Memory,Unnamed: 246
0,'em,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.99351,0.0,NaN,NaN,NaN,NaN,NaN
1,'neath,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.99351,0.0,NaN,NaN,NaN,NaN,NaN
2,'re,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.99351,0.0,NaN,NaN,NaN,NaN,NaN
3,'shun,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.99351,0.0,NaN,NaN,NaN,NaN,NaN
4,'tis,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,-0.99351,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105988,_clairs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105989,_clat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105990,_cru,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105991,_lan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105992,_p_e,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
List_vars = pd.read_excel('/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/SemanticVars/codes/SemanticVarsList.xlsx')

List_vars = list(List_vars.Variable.values)+['Valence_NRC','Arousal_NRC','Dominance_NRC']
dfs_timing = []
for i, word in zip(dfs.index,dfs.word):
    df_tmp = df_scope.loc[df_scope.Word==word,List_vars].reset_index(drop=True)
    if len(df_tmp) == 0:
        df_tmp.loc[0] = np.nan
    df_tmp_word = pd.concat([dfs.loc[i],df_tmp.loc[0]]).to_frame().T
    dfs_timing.append(df_tmp_word)

dfs_timing = pd.concat(dfs_timing,ignore_index=True)
dfs_timing

,raw,word,onset,offset,audio,PoS_tag_full,AoA_LWV,OLD20,PLD20,Nsenses_WordNet,...,Sem_N,Sem_Diversity,Consistency_Token_FF,Consistency_Type_FF,Consistency_Token_FB,Consistency_Type_FB,ROOT1_FamSize,Valence_NRC,Arousal_NRC,Dominance_NRC
0,Koko 1.700 2.300,Koko,1.700,2.300,Jacob_Koko,NNP,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,did 4.500 4.900,did,4.500,4.900,Jacob_Koko,VBD,NaN,1.25,1.0,13.0,...,9250.0,2.126914,0.832616,0.84104,0.866084,0.867352,6.0,NaN,NaN,NaN
2,you 4.900 5,you,4.900,5,Jacob_Koko,PRP,NaN,1.85,1.0,0.0,...,8468.0,2.0304,0.609223,0.606674,0.433655,0.391659,1.0,NaN,NaN,NaN
3,know 5 5.200,know,5,5.200,Jacob_Koko,VBP,4.685078,1.65,1.0,12.0,...,8162.0,1.98089,0.606487,0.588867,0.238291,0.228893,20.0,0.765,0.361,0.704
4,that 5.200 5.500,that,5.200,5.500,Jacob_Koko,IN,NaN,1.65,1.25,0.0,...,9891.0,2.350962,0.339747,0.301681,0.492444,0.468225,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43398,to 355 355.400,to,355,355.400,Allison_MetaphorsRepeatedNames,TO,NaN,1.15,1.0,0.0,...,9796.0,2.372819,0.405733,0.403407,0.451664,0.439392,10.0,NaN,NaN,NaN
43399,look 355.400 355.600,look,355.400,355.600,Allison_MetaphorsRepeatedNames,VB,4.208655,1.4,1.1,14.0,...,8543.0,2.017486,0.717252,0.700258,0.64749,0.632982,7.0,0.719,0.429,0.615
43400,for 355.600 355.800,for,355.600,355.800,Allison_MetaphorsRepeatedNames,IN,NaN,1.3,1.0,0.0,...,9733.0,2.380212,0.491213,0.484976,0.435592,0.426956,3.0,NaN,NaN,NaN
43401,another 355.800 355.900,another,355.800,355.900,Allison_MetaphorsRepeatedNames,DT,4.64812,2.55,2.7,1.0,...,9852.0,2.291655,0.646291,0.640534,0.596845,0.596409,1.0,NaN,NaN,NaN
43402,house 355.900 356.500,house,355.900,356.500,Allison_MetaphorsRepeatedNames,NN,3.241765,1.6,1.65,14.0,...,8838.0,2.007701,0.751103,0.794808,0.678989,0.701715,91.0,0.587,0.135,0.533

In [103]:
dfs_timing.to_csv('/work/desai-lab/xuanyang/Project/ABC/fMRI/fmri_pass/ABC_passage_timings.csv',index=False)

In [105]:
Dir_project = '/work/desai-lab/ABC_dataset'
Dir_derivatives = os.path.join(Dir_project,'derivatives')
Dir_smooth = os.path.join(Dir_derivatives,'afni-smooth')
Dir_fmriprep = os.path.join(Dir_derivatives,'fmriprep')
Dir_raw = '/work/desai-lab/ABCAI/raw/'

df_subject = pd.read_csv('/work/desai-lab/xuanyang/Project/ABC/fMRI/fmri_pass/master_subjects_fmri_passage_complete.csv')
df_subject = df_subject[['subID','sesID','story_english','Hearing_max','ACC','age_dayofday1testing']]
df_subject

,subID,sesID,story_english,Hearing_max,ACC,age_dayofday1testing
0,sub-1006,visit01,Brandi_TaleofTwoCountries.wav,0.0,1.00,61.0
1,sub-1007,visit01,Jack_ProfessionalDecline.wav,1.0,0.50,69.0
2,sub-1008,visit01,Jacob_FairyTree.wav,1.0,0.75,77.0
3,sub-1009,visit01,Jacob_HowCouldYou.wav,4.0,1.00,75.0
4,sub-1011,visit01,Jacob_TigerandLion.wav,1.0,0.75,66.0
...,...,...,...,...,...,...
109,sub-1183,visit01,Brandi_Roswell.wav,0.0,0.75,21.0
110,sub-1185,visit01,Allison_MetaphorsPronouns.wav,1.0,1.00,20.0
111,sub-1187,visit01,Allison_BulliesPronouns.wav,0.0,1.00,22.0
112,sub-1194,visit01,Jack_ProfessionalDecline.wav,1.0,0.25,46.0
113,sub-1197,visit01,Jacob_Koko.wav,0.0,1.00,45.0

In [112]:
for i,subID,story in zip(df_subject.index,df_subject.subID,df_subject.story_english):
    
    audio = story.replace('.wav','')
    if audio == 'Jacob_Bradford':
        audio = 'Jacob_BradfordBull'
    df_tmp = dfs_timing.loc[dfs_timing.audio==audio]

In [114]:
df_subject.story_english.unique()

array(['Brandi_TaleofTwoCountries.wav', 'Jack_ProfessionalDecline.wav',
       'Jacob_FairyTree.wav', 'Jacob_HowCouldYou.wav',
       'Jacob_TigerandLion.wav', 'Jacob_UserFriendly.wav',
       'Brandi_BradfordBull.wav', 'Jacob_EmpireState.wav',
       'Brandi_FairyTree.wav', 'Jacob_Koko.wav', 'Jacob_Aqua.wav',
       'Jacob_Bradford.wav', 'Brandi_Elvis.wav',
       'Brandi_TigerandLion.wav', 'Allison_AgedMother.wav',
       'Allison_BiggestWastes.wav', 'Jack_EmotionSentences_953.wav',
       'Jack_FirstConcert.wav', 'Jacob_FireSelected.wav',
       'Brandi_Aqua.wav', 'Jack_MetaphorsPronouns.wav',
       'Allison_MetaphorsRepeatedNames.wav',
       'Allison_BulliesPronouns.wav', 'Allison_BulliesRepeatedNames.wav',
       'Brandi_HappyDay.wav', 'Brandi_FirstConcert.wav',
       'Jack_Roswell.wav', 'Jacob_HappyDay.wav',
       'Jack_MetaphorsRepeatedNames.wav', 'Brandi_EmpireState.wav',
       'Brandi_HowCouldYou.wav', 'Jacob_TaleofTwoCountries.wav',
       'Brandi_Roswell.wav', 'Allison_MetaphorsPronouns.wav'],
      dtype=object)